import PopularMovies from '../components/PopularMovies';
import Head from 'next/head';

export default function Home({ movies }) {
  return (
    <div>
      <Head>
        <title>Find your next movie</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <PopularMovies movies={movies} title='Popular movies' />
    </div>
  );
}

export const getServerSideProps = async () => {
  const url = `https://api.themoviedb.org/3/movie/popular?api_key=${process.env.MOVIE_API}&language=en-US&page=1`;
  const res = await fetch(url);
  const movies = await res.json();

  return {
    props: {
      movies,
    },
  };
};
